spring:
  application:
    name: event-management-service
  datasource:
    username: "postgres"
    password: "123"
    url: "jdbc:postgresql://127.0.0.1:5432/event-management"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    generate-ddl: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            type:
              mapping: created_event:com.event.eventmanagementservice.topic.CreatedEvents
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 0
  tomcat:
    max-swallow-size: -1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

events:
  image:
    path: C:/Users/Yagizcan/Desktop/event-app/img/event

